shoulder_pan_gains: &shoulder_pan_gains
  p: 50.0
  d: 5.0
  i: 0.0
  i_clamp: 0.0
  mass: 3.3
  proxy:
    lambda: 3.0
    acc_converge: 1.5
    vel_limit: 2.088
    effort_limit: 11.8

shoulder_lift_gains: &shoulder_lift_gains
  p: 60.0
  d: 12.0
  i: 0.0
  i_clamp: 0.0
  mass: 2.0
  proxy:
    lambda: 3.0
    acc_converge: 1.5
    vel_limit: 2.082
    effort_limit: 8.0

upper_arm_roll_gains: &upper_arm_roll_gains
  p: 45.0
  d: 3.0
  i: 0.0
  i_clamp: 0.0

elbow_flex_gains: &elbow_flex_gains
  p: 40.0
  d: 2.0
  i: 0.0
  i_clamp: 0.0

forearm_roll_gains: &forearm_roll_gains
  p: 20.0
  d: 2.0
  i: 0.0
  i_clamp: 0.0

wrist_flex_gains: &wrist_flex_gains
  p: 13.0
  d: 0.5
  i: 0.0
  i_clamp: 0.0

wrist_roll_gains: &wrist_roll_gains
  p: 6.25
  d: 0.25
  i: 0.0
  i_clamp: 0.0

r_arm_controller_loose:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints:
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    - r_forearm_roll_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
  gains:
    r_shoulder_pan_joint:    *shoulder_pan_gains
    r_shoulder_lift_joint:   *shoulder_lift_gains
    r_upper_arm_roll_joint:  *upper_arm_roll_gains
    r_elbow_flex_joint:      *elbow_flex_gains
    r_forearm_roll_joint:    *forearm_roll_gains
    r_wrist_flex_joint:      *wrist_flex_gains
    r_wrist_roll_joint:      *wrist_roll_gains
  joint_trajectory_action_node:
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint
    constraints:
      goal_time: 0.6
      r_shoulder_pan_joint:
        goal: 0.02
      r_shoulder_lift_joint:
        goal: 0.02
      r_upper_arm_roll_joint:
        goal: 0.02
      r_elbow_flex_joint:
        goal: 0.02
      r_forearm_roll_joint:
        goal: 0.02
      r_wrist_flex_joint:
        goal: 0.02
      r_wrist_roll_joint:
        goal: 0.02
  
l_arm_controller_loose:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints:
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_forearm_roll_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
  gains:
    l_shoulder_pan_joint:    *shoulder_pan_gains
    l_shoulder_lift_joint:   *shoulder_lift_gains
    l_upper_arm_roll_joint:  *upper_arm_roll_gains
    l_elbow_flex_joint:      *elbow_flex_gains
    l_forearm_roll_joint:    *forearm_roll_gains
    l_wrist_flex_joint:      *wrist_flex_gains
    l_wrist_roll_joint:      *wrist_roll_gains
  joint_trajectory_action_node:
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    constraints:
      goal_time: 0.6
      l_shoulder_pan_joint:
        goal: 0.02
      l_shoulder_lift_joint:
        goal: 0.02
      l_upper_arm_roll_joint:
        goal: 0.02
      l_elbow_flex_joint:
        goal: 0.02
      l_forearm_roll_joint:
        goal: 0.02
      l_wrist_flex_joint:
        goal: 0.02
      l_wrist_roll_joint:
        goal: 0.02
