/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-multimaster-experimental-0.2.1/debian/ros-groovy-multimaster-experimental/opt/ros/groovy/stacks/multimaster_experimental/app_manager/srv/GetInstallationState.srv */
#ifndef APP_MANAGER_SERVICE_GETINSTALLATIONSTATE_H
#define APP_MANAGER_SERVICE_GETINSTALLATIONSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "app_manager/ExchangeApp.h"
#include "app_manager/ExchangeApp.h"

namespace app_manager
{
template <class ContainerAllocator>
struct GetInstallationStateRequest_ {
  typedef GetInstallationStateRequest_<ContainerAllocator> Type;

  GetInstallationStateRequest_()
  : remote_update(false)
  {
  }

  GetInstallationStateRequest_(const ContainerAllocator& _alloc)
  : remote_update(false)
  {
  }

  typedef uint8_t _remote_update_type;
  uint8_t remote_update;


  typedef boost::shared_ptr< ::app_manager::GetInstallationStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_manager::GetInstallationStateRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetInstallationStateRequest
typedef  ::app_manager::GetInstallationStateRequest_<std::allocator<void> > GetInstallationStateRequest;

typedef boost::shared_ptr< ::app_manager::GetInstallationStateRequest> GetInstallationStateRequestPtr;
typedef boost::shared_ptr< ::app_manager::GetInstallationStateRequest const> GetInstallationStateRequestConstPtr;



template <class ContainerAllocator>
struct GetInstallationStateResponse_ {
  typedef GetInstallationStateResponse_<ContainerAllocator> Type;

  GetInstallationStateResponse_()
  : installed_apps()
  , available_apps()
  {
  }

  GetInstallationStateResponse_(const ContainerAllocator& _alloc)
  : installed_apps(_alloc)
  , available_apps(_alloc)
  {
  }

  typedef std::vector< ::app_manager::ExchangeApp_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::app_manager::ExchangeApp_<ContainerAllocator> >::other >  _installed_apps_type;
  std::vector< ::app_manager::ExchangeApp_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::app_manager::ExchangeApp_<ContainerAllocator> >::other >  installed_apps;

  typedef std::vector< ::app_manager::ExchangeApp_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::app_manager::ExchangeApp_<ContainerAllocator> >::other >  _available_apps_type;
  std::vector< ::app_manager::ExchangeApp_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::app_manager::ExchangeApp_<ContainerAllocator> >::other >  available_apps;


  typedef boost::shared_ptr< ::app_manager::GetInstallationStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_manager::GetInstallationStateResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetInstallationStateResponse
typedef  ::app_manager::GetInstallationStateResponse_<std::allocator<void> > GetInstallationStateResponse;

typedef boost::shared_ptr< ::app_manager::GetInstallationStateResponse> GetInstallationStateResponsePtr;
typedef boost::shared_ptr< ::app_manager::GetInstallationStateResponse const> GetInstallationStateResponseConstPtr;


struct GetInstallationState
{

typedef GetInstallationStateRequest Request;
typedef GetInstallationStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetInstallationState
} // namespace app_manager

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::app_manager::GetInstallationStateRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::app_manager::GetInstallationStateRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::app_manager::GetInstallationStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f7e64723808960ca985ba81f45f1b8a7";
  }

  static const char* value(const  ::app_manager::GetInstallationStateRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf7e64723808960caULL;
  static const uint64_t static_value2 = 0x985ba81f45f1b8a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::app_manager::GetInstallationStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/GetInstallationStateRequest";
  }

  static const char* value(const  ::app_manager::GetInstallationStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::app_manager::GetInstallationStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool remote_update\n\
\n\
";
  }

  static const char* value(const  ::app_manager::GetInstallationStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::app_manager::GetInstallationStateRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::app_manager::GetInstallationStateResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::app_manager::GetInstallationStateResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::app_manager::GetInstallationStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "46d45bbda08250199267aff8c0ee8c41";
  }

  static const char* value(const  ::app_manager::GetInstallationStateResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x46d45bbda0825019ULL;
  static const uint64_t static_value2 = 0x9267aff8c0ee8c41ULL;
};

template<class ContainerAllocator>
struct DataType< ::app_manager::GetInstallationStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/GetInstallationStateResponse";
  }

  static const char* value(const  ::app_manager::GetInstallationStateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::app_manager::GetInstallationStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ExchangeApp[] installed_apps\n\
ExchangeApp[] available_apps\n\
\n\
================================================================================\n\
MSG: app_manager/ExchangeApp\n\
# app name\n\
string name\n\
# user-friendly display name of application\n\
string display_name\n\
# the version of the package currently installed\n\
string version\n\
# latest version of the package avaliable\n\
string latest_version\n\
# the detailed description of the app\n\
string description\n\
# icon for showing app\n\
Icon icon\n\
# hidden apps are not show - used for cases where multiple apps are in a deb\n\
bool hidden\n\
================================================================================\n\
MSG: app_manager/Icon\n\
# Image data format.  \"jpeg\" or \"png\"\n\
string format\n\
\n\
# Image data.\n\
uint8[] data\n\
\n\
";
  }

  static const char* value(const  ::app_manager::GetInstallationStateResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::app_manager::GetInstallationStateRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.remote_update);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetInstallationStateRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::app_manager::GetInstallationStateResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.installed_apps);
    stream.next(m.available_apps);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetInstallationStateResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<app_manager::GetInstallationState> {
  static const char* value() 
  {
    return "28f0a7294f6241e2423a9382e3c76987";
  }

  static const char* value(const app_manager::GetInstallationState&) { return value(); } 
};

template<>
struct DataType<app_manager::GetInstallationState> {
  static const char* value() 
  {
    return "app_manager/GetInstallationState";
  }

  static const char* value(const app_manager::GetInstallationState&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<app_manager::GetInstallationStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "28f0a7294f6241e2423a9382e3c76987";
  }

  static const char* value(const app_manager::GetInstallationStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<app_manager::GetInstallationStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/GetInstallationState";
  }

  static const char* value(const app_manager::GetInstallationStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<app_manager::GetInstallationStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "28f0a7294f6241e2423a9382e3c76987";
  }

  static const char* value(const app_manager::GetInstallationStateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<app_manager::GetInstallationStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/GetInstallationState";
  }

  static const char* value(const app_manager::GetInstallationStateResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // APP_MANAGER_SERVICE_GETINSTALLATIONSTATE_H

