/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-multimaster-experimental-0.2.1/debian/ros-groovy-multimaster-experimental/opt/ros/groovy/stacks/multimaster_experimental/app_manager/srv/ListApps.srv */
#ifndef APP_MANAGER_SERVICE_LISTAPPS_H
#define APP_MANAGER_SERVICE_LISTAPPS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "app_manager/App.h"
#include "app_manager/App.h"

namespace app_manager
{
template <class ContainerAllocator>
struct ListAppsRequest_ {
  typedef ListAppsRequest_<ContainerAllocator> Type;

  ListAppsRequest_()
  {
  }

  ListAppsRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::app_manager::ListAppsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_manager::ListAppsRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ListAppsRequest
typedef  ::app_manager::ListAppsRequest_<std::allocator<void> > ListAppsRequest;

typedef boost::shared_ptr< ::app_manager::ListAppsRequest> ListAppsRequestPtr;
typedef boost::shared_ptr< ::app_manager::ListAppsRequest const> ListAppsRequestConstPtr;



template <class ContainerAllocator>
struct ListAppsResponse_ {
  typedef ListAppsResponse_<ContainerAllocator> Type;

  ListAppsResponse_()
  : running_apps()
  , available_apps()
  {
  }

  ListAppsResponse_(const ContainerAllocator& _alloc)
  : running_apps(_alloc)
  , available_apps(_alloc)
  {
  }

  typedef std::vector< ::app_manager::App_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::app_manager::App_<ContainerAllocator> >::other >  _running_apps_type;
  std::vector< ::app_manager::App_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::app_manager::App_<ContainerAllocator> >::other >  running_apps;

  typedef std::vector< ::app_manager::App_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::app_manager::App_<ContainerAllocator> >::other >  _available_apps_type;
  std::vector< ::app_manager::App_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::app_manager::App_<ContainerAllocator> >::other >  available_apps;


  typedef boost::shared_ptr< ::app_manager::ListAppsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_manager::ListAppsResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ListAppsResponse
typedef  ::app_manager::ListAppsResponse_<std::allocator<void> > ListAppsResponse;

typedef boost::shared_ptr< ::app_manager::ListAppsResponse> ListAppsResponsePtr;
typedef boost::shared_ptr< ::app_manager::ListAppsResponse const> ListAppsResponseConstPtr;


struct ListApps
{

typedef ListAppsRequest Request;
typedef ListAppsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ListApps
} // namespace app_manager

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::app_manager::ListAppsRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::app_manager::ListAppsRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::app_manager::ListAppsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::app_manager::ListAppsRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::app_manager::ListAppsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/ListAppsRequest";
  }

  static const char* value(const  ::app_manager::ListAppsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::app_manager::ListAppsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::app_manager::ListAppsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::app_manager::ListAppsRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::app_manager::ListAppsResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::app_manager::ListAppsResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::app_manager::ListAppsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8a71ede6bf51909653c7c551f462cb30";
  }

  static const char* value(const  ::app_manager::ListAppsResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8a71ede6bf519096ULL;
  static const uint64_t static_value2 = 0x53c7c551f462cb30ULL;
};

template<class ContainerAllocator>
struct DataType< ::app_manager::ListAppsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/ListAppsResponse";
  }

  static const char* value(const  ::app_manager::ListAppsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::app_manager::ListAppsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "App[] running_apps\n\
App[] available_apps\n\
\n\
================================================================================\n\
MSG: app_manager/App\n\
# app name\n\
string name\n\
# user-friendly display name of application\n\
string display_name\n\
# icon for showing app\n\
Icon icon\n\
# ordered list (by preference) of client applications to interact with this robot app.  \n\
ClientApp[] client_apps\n\
\n\
================================================================================\n\
MSG: app_manager/Icon\n\
# Image data format.  \"jpeg\" or \"png\"\n\
string format\n\
\n\
# Image data.\n\
uint8[] data\n\
\n\
================================================================================\n\
MSG: app_manager/ClientApp\n\
# like \"android\" or \"web\" or \"linux\"\n\
string client_type\n\
\n\
# like \"intent = ros.android.teleop\" and \"accelerometer = true\", used to choose which ClientApp to use\n\
KeyValue[] manager_data\n\
\n\
# parameters which just get passed through to the client app.\n\
KeyValue[] app_data\n\
\n\
================================================================================\n\
MSG: app_manager/KeyValue\n\
string key\n\
string value\n\
\n\
";
  }

  static const char* value(const  ::app_manager::ListAppsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::app_manager::ListAppsRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ListAppsRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::app_manager::ListAppsResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.running_apps);
    stream.next(m.available_apps);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ListAppsResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<app_manager::ListApps> {
  static const char* value() 
  {
    return "8a71ede6bf51909653c7c551f462cb30";
  }

  static const char* value(const app_manager::ListApps&) { return value(); } 
};

template<>
struct DataType<app_manager::ListApps> {
  static const char* value() 
  {
    return "app_manager/ListApps";
  }

  static const char* value(const app_manager::ListApps&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<app_manager::ListAppsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8a71ede6bf51909653c7c551f462cb30";
  }

  static const char* value(const app_manager::ListAppsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<app_manager::ListAppsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/ListApps";
  }

  static const char* value(const app_manager::ListAppsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<app_manager::ListAppsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8a71ede6bf51909653c7c551f462cb30";
  }

  static const char* value(const app_manager::ListAppsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<app_manager::ListAppsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/ListApps";
  }

  static const char* value(const app_manager::ListAppsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // APP_MANAGER_SERVICE_LISTAPPS_H

