/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-multimaster-experimental-0.2.1/debian/ros-groovy-multimaster-experimental/opt/ros/groovy/stacks/multimaster_experimental/app_manager/srv/UninstallApp.srv */
#ifndef APP_MANAGER_SERVICE_UNINSTALLAPP_H
#define APP_MANAGER_SERVICE_UNINSTALLAPP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace app_manager
{
template <class ContainerAllocator>
struct UninstallAppRequest_ {
  typedef UninstallAppRequest_<ContainerAllocator> Type;

  UninstallAppRequest_()
  : name()
  {
  }

  UninstallAppRequest_(const ContainerAllocator& _alloc)
  : name(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;


  typedef boost::shared_ptr< ::app_manager::UninstallAppRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_manager::UninstallAppRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct UninstallAppRequest
typedef  ::app_manager::UninstallAppRequest_<std::allocator<void> > UninstallAppRequest;

typedef boost::shared_ptr< ::app_manager::UninstallAppRequest> UninstallAppRequestPtr;
typedef boost::shared_ptr< ::app_manager::UninstallAppRequest const> UninstallAppRequestConstPtr;



template <class ContainerAllocator>
struct UninstallAppResponse_ {
  typedef UninstallAppResponse_<ContainerAllocator> Type;

  UninstallAppResponse_()
  : uninstalled(false)
  , message()
  {
  }

  UninstallAppResponse_(const ContainerAllocator& _alloc)
  : uninstalled(false)
  , message(_alloc)
  {
  }

  typedef uint8_t _uninstalled_type;
  uint8_t uninstalled;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  message;


  typedef boost::shared_ptr< ::app_manager::UninstallAppResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_manager::UninstallAppResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct UninstallAppResponse
typedef  ::app_manager::UninstallAppResponse_<std::allocator<void> > UninstallAppResponse;

typedef boost::shared_ptr< ::app_manager::UninstallAppResponse> UninstallAppResponsePtr;
typedef boost::shared_ptr< ::app_manager::UninstallAppResponse const> UninstallAppResponseConstPtr;


struct UninstallApp
{

typedef UninstallAppRequest Request;
typedef UninstallAppResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct UninstallApp
} // namespace app_manager

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::app_manager::UninstallAppRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::app_manager::UninstallAppRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::app_manager::UninstallAppRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const  ::app_manager::UninstallAppRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::app_manager::UninstallAppRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/UninstallAppRequest";
  }

  static const char* value(const  ::app_manager::UninstallAppRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::app_manager::UninstallAppRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
string name\n\
\n\
";
  }

  static const char* value(const  ::app_manager::UninstallAppRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::app_manager::UninstallAppResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::app_manager::UninstallAppResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::app_manager::UninstallAppResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "335f3f18ef026f9358ef38ecb7785332";
  }

  static const char* value(const  ::app_manager::UninstallAppResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x335f3f18ef026f93ULL;
  static const uint64_t static_value2 = 0x58ef38ecb7785332ULL;
};

template<class ContainerAllocator>
struct DataType< ::app_manager::UninstallAppResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/UninstallAppResponse";
  }

  static const char* value(const  ::app_manager::UninstallAppResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::app_manager::UninstallAppResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
bool uninstalled\n\
string message\n\
\n\
\n\
";
  }

  static const char* value(const  ::app_manager::UninstallAppResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::app_manager::UninstallAppRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct UninstallAppRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::app_manager::UninstallAppResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.uninstalled);
    stream.next(m.message);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct UninstallAppResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<app_manager::UninstallApp> {
  static const char* value() 
  {
    return "1694b710073aaad53ae6c852885793c6";
  }

  static const char* value(const app_manager::UninstallApp&) { return value(); } 
};

template<>
struct DataType<app_manager::UninstallApp> {
  static const char* value() 
  {
    return "app_manager/UninstallApp";
  }

  static const char* value(const app_manager::UninstallApp&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<app_manager::UninstallAppRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1694b710073aaad53ae6c852885793c6";
  }

  static const char* value(const app_manager::UninstallAppRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<app_manager::UninstallAppRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/UninstallApp";
  }

  static const char* value(const app_manager::UninstallAppRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<app_manager::UninstallAppResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1694b710073aaad53ae6c852885793c6";
  }

  static const char* value(const app_manager::UninstallAppResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<app_manager::UninstallAppResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/UninstallApp";
  }

  static const char* value(const app_manager::UninstallAppResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // APP_MANAGER_SERVICE_UNINSTALLAPP_H

