/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-multimaster-experimental-0.2.1/debian/ros-groovy-multimaster-experimental/opt/ros/groovy/stacks/multimaster_experimental/app_manager/msg/KeyValue.msg */
#ifndef APP_MANAGER_MESSAGE_KEYVALUE_H
#define APP_MANAGER_MESSAGE_KEYVALUE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace app_manager
{
template <class ContainerAllocator>
struct KeyValue_ {
  typedef KeyValue_<ContainerAllocator> Type;

  KeyValue_()
  : key()
  , value()
  {
  }

  KeyValue_(const ContainerAllocator& _alloc)
  : key(_alloc)
  , value(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _key_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  key;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  value;


  typedef boost::shared_ptr< ::app_manager::KeyValue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_manager::KeyValue_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct KeyValue
typedef  ::app_manager::KeyValue_<std::allocator<void> > KeyValue;

typedef boost::shared_ptr< ::app_manager::KeyValue> KeyValuePtr;
typedef boost::shared_ptr< ::app_manager::KeyValue const> KeyValueConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::app_manager::KeyValue_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::app_manager::KeyValue_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace app_manager

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::app_manager::KeyValue_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::app_manager::KeyValue_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::app_manager::KeyValue_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cf57fdc6617a881a88c16e768132149c";
  }

  static const char* value(const  ::app_manager::KeyValue_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcf57fdc6617a881aULL;
  static const uint64_t static_value2 = 0x88c16e768132149cULL;
};

template<class ContainerAllocator>
struct DataType< ::app_manager::KeyValue_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/KeyValue";
  }

  static const char* value(const  ::app_manager::KeyValue_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::app_manager::KeyValue_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string key\n\
string value\n\
\n\
";
  }

  static const char* value(const  ::app_manager::KeyValue_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::app_manager::KeyValue_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.key);
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct KeyValue_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::app_manager::KeyValue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::app_manager::KeyValue_<ContainerAllocator> & v) 
  {
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.key);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // APP_MANAGER_MESSAGE_KEYVALUE_H

